# Generated by Django 4.1.5 on 2023-02-16 19:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inicioApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Permisos_emision',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('id_permisos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inicioApp.permisos')),
            ],
            options={
                'db_table': 'permisos_emision',
            },
        ),
    ]
